openapi: 3.0.0
info:
  title: lambda-express-sequelize
  description: documentaci√≥n lambda-express-sequelize
  version: 1.0.0
  servers:
    - http://localhost:4000
paths:
  /api/Client:
    get:
      tags:
        - Client
      parameters: []
      requestBody: null
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                example:
                  - uuid: 2cbe2738-ae6b-466b-b09a-4fd4a4d4fdde
                    nombre: cliente nombre
                  - uuid: 4f32f432-021d-4165-b235-ab2e068aec32
                    nombre: cliente nombre
                  - uuid: fff8ace3-efb2-42dd-b7ef-3f31de5b56aa
                    nombre: cliente nombre
    post:
      tags:
        - Client
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example: &ref_0
                uuid: 29f32641-565c-419d-80a1-3ed9005d5c4a
                nombre: cliente nombre
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                example: *ref_0
  /api/Client/{uuid}:
    put:
      tags:
        - Client
      parameters:
        - name: uuid
          in: path
          type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example: &ref_1
                uuid: fff8ace3-efb2-42dd-b7ef-3f31de5b56aa
                nombre: cliente nombre
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                example: *ref_1
  /api/Client/filter?nombre={nombre}:
    get:
      tags:
        - Client
      parameters:
        - name: nombre
          in: path
          type: string
          required: false
      requestBody: null
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                example:
                  - uuid: 29f32641-565c-419d-80a1-3ed9005d5c4a
                    nombre: cliente nombre
                  - uuid: 2cbe2738-ae6b-466b-b09a-4fd4a4d4fdde
                    nombre: cliente nombre
                  - uuid: 4f32f432-021d-4165-b235-ab2e068aec32
                    nombre: cliente nombre
                  - uuid: fff8ace3-efb2-42dd-b7ef-3f31de5b56aa
                    nombre: cliente nombre
  /api/User:
    get:
      tags:
        - User
      parameters: []
      requestBody: null
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                example:
                  - uuid: 076870fa-3764-48ed-a833-2e32d6689e6d
                    nombre: usuario nombre
                  - uuid: 60d8431e-78be-434d-b8e0-0bf4f9726bab
                    nombre: usuario nombre
                  - uuid: 8d3dc470-0dd6-4c78-acea-8e0da01e8463
                    nombre: usuario nombre
    post:
      tags:
        - User
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example: &ref_2
                uuid: 893eb666-270f-491d-81d3-49dd9677534b
                nombre: Esteban Quitero
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                example: *ref_2
  /api/User/{uuid}:
    put:
      tags:
        - User
      parameters:
        - name: uuid
          in: path
          type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example: &ref_3
                uuid: 60d8431e-78be-434d-b8e0-0bf4f9726bab
                nombre: Emily Quintero
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                example: *ref_3
  /api/User/filter?nombre={nombre}:
    get:
      tags:
        - User
      parameters:
        - name: nombre
          in: path
          type: string
          required: false
      requestBody: null
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                example:
                  - uuid: 076870fa-3764-48ed-a833-2e32d6689e6d
                    nombre: usuario nombre
                  - uuid: 8d3dc470-0dd6-4c78-acea-8e0da01e8463
                    nombre: usuario nombre
components:
  parameters: {}
  definitions: {}
  schemas:
    usuario:
      type: object
      properties:
        uuid:
          type: string
          required: true
          description: identificador universal unico para la tabal usuario
          example: 893eb666-270f-491d-81d3-49dd9677534b
        nombre:
          type: string
          required: true
          description: nombre de usuario
          example: Esteban Quitero
    cliente:
      type: object
      properties:
        uuid:
          type: string
          required: true
          description: identificador universal unico para la tabal cliente
          example: 29f32641-565c-419d-80a1-3ed9005d5c4a
        nombre:
          type: string
          required: true
          description: nombre del clinete
          example: cliente nombre
  tags:
    - User
    - Client
